# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://gb-simon.github.io/
baseurl: /sustain/
title: Gonzalo Simon
author: Chris Turner
description: Personal blog and resume
avatar: profile.png
email: aguilarsimon01@gmail.com
github: gb-simon # username
twitter: _gonzalosimon
linkedin: Gonzalo Simon Aguilar
stackoverflow: gonzalosimon   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: gonzalosimon
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
